### ISSUE TITLE
CentOS 5 box has wrong DNS conf

### ISSUE THREAD

**Issue by ttres** [instruct-br/puppet-toolkit#36]
The centos-5 Vagrant box is failing to install the puppet-agent package because the resolution of names is misconfigured.
The `/etc/resolv.conf` file has the address `192.168.122.1` as nameserver, when it should be `10.0.2.3`, for internal Vagrant network.

**Comment by gutocarvalho** [comment]
I don't think it's a box issue because the dhcp client should configure this file properly.

Anyways, I'll take a look ;)

**Comment by gutocarvalho** [comment]
1) Using the box directly everything works fine
2) The problem happens when we are provisioning the box via puppet-toolkit

I confirm the issue, still checking...

**Comment by ttres** [comment]
Ok, [this](http://tickets.opscode.com/browse/BENTO-13) is the cause, and [this](https://github.com/chef/bento/pull/75) is the solution: uninstall `kudzu` package from the box.
```
Installed Packages
Name       : kudzu
Arch       : x86_64
Version    : 1.2.57.1.26
Release    : 7.el5.centos
Size       : 455 k
Repo       : installed
Summary    : The CentOS Linux hardware probing tool.
URL        : http://fedora.redhat.com/projects/additional-projects/kudzu/
License    : GPL
Description: Kudzu is a hardware probing tool run at system boot time to determine
           : what hardware has been added or removed from the system.
```

The same problem is happening with the official Puppet CentOS 5 (puppetlabs/centos-5.11-64-puppet, suggested by @mciurcio ) box:
```
# yum info kudzu
Installed Packages
Name       : kudzu
Arch       : x86_64
Version    : 1.2.57.1.26
Release    : 7.el5.centos
Size       : 455 k
Repo       : installed
Summary    : The CentOS Linux hardware probing tool.
URL        : http://fedora.redhat.com/projects/additional-projects/kudzu/
License    : GPL
Description: Kudzu is a hardware probing tool run at system boot time to determine
           : what hardware has been added or removed from the system.
```

@gutocarvalho looks like the box works for you because you're the packager, so the network config inside the box is yours, but will not work for anyone else. ;-)

**Comment by ttres** [comment]
Version 1.0.1 of box `gutocarvalho/oracle5x64nocm` fixes this.
Closing.
